# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20160508_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='rating',
            field=models.FloatField(),
        ),
    ]
